export type Vendor = {
  id: string;
  name: string;
  category: string;
  description: string;
  eta: string;
  rating: number;
  isOpen: boolean;
  accent: string;
};

export type FoodItem = {
  id: string;
  name: string;
  vendor: string;
  vendorId: string;
  price: number;
  category: string;
  description: string;
  available: boolean;
  accent: string;
  imageUrl?: string;
};

export const featuredVendors: Vendor[] = [
  {
    id: "fresh-bites",
    name: "Fresh Bites",
    category: "Fast Food",
    description: "Crispy wraps and student favourites for quick pickup.",
    eta: "Ready in 8 mins",
    rating: 4.8,
    isOpen: true,
    accent: "from-violet-500 to-purple-600",
  },
  {
    id: "mamas-corner",
    name: "Mama's Corner",
    category: "Traditional Meals",
    description: "Hot bowls, comforting flavours, and classic comfort food.",
    eta: "Ready in 10 mins",
    rating: 4.9,
    isOpen: true,
    accent: "from-fuchsia-500 to-violet-600",
  },
  {
    id: "student-cafe",
    name: "Student Café",
    category: "Campus Café",
    description: "Light meals, coffee, and snacks for busy study days.",
    eta: "Ready in 5 mins",
    rating: 4.7,
    isOpen: true,
    accent: "from-violet-400 to-indigo-500",
  },
  {
    id: "sunset-snacks",
    name: "Sunset Snacks",
    category: "Snacks",
    description: "Quick bites and drinks for between lectures.",
    eta: "Ready in 4 mins",
    rating: 4.6,
    isOpen: true,
    accent: "from-purple-400 to-pink-500",
  },
];

export const popularItems: FoodItem[] = [
  {
    id: "chicken-wrap",
    name: "Chicken Wrap",
    vendor: "Fresh Bites",
    vendorId: "fresh-bites",
    price: 45,
    category: "Meals",
    description: "Grilled chicken, slaw, and chilli mayo.",
    available: true,
    accent: "from-violet-100 to-violet-200",
    imageUrl: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "beef-bowl",
    name: "Beef Rice Bowl",
    vendor: "Mama's Corner",
    vendorId: "mamas-corner",
    price: 62,
    category: "Meals",
    description: "Tender beef and vegetables over steamed rice.",
    available: true,
    accent: "from-fuchsia-100 to-violet-100",
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "iced-latte",
    name: "Iced Latte",
    vendor: "Student Café",
    vendorId: "student-cafe",
    price: 28,
    category: "Drinks",
    description: "Smooth, chilled, and campus-ready.",
    available: true,
    accent: "from-violet-50 to-indigo-100",
    imageUrl: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "cheese-scone",
    name: "Cheese Scone",
    vendor: "Sunset Snacks",
    vendorId: "sunset-snacks",
    price: 22,
    category: "Snacks",
    description: "Buttery, warm, and satisfying.",
    available: false,
    accent: "from-violet-100 to-pink-100",
    imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=80",
  },
];

export const vendorMenuItems = [
  { id: "1", name: "Chicken Wrap", category: "Meals", price: 45, available: true, imageUrl: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=80" },
  { id: "2", name: "Beef Rice Bowl", category: "Meals", price: 62, available: true, imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80" },
  { id: "6", name: "Pap & Chakalaka", category: "African Meals", price: 48, available: true, imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80" },
  { id: "7", name: "Beef Bunny Chow", category: "African Meals", price: 58, available: true, imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80" },
  { id: "8", name: "Vetkoek & Mince", category: "Street Food", price: 42, available: true, imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=80" },
  { id: "9", name: "Chicken samoosas", category: "Snacks", price: 30, available: true, imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80" },
  { id: "12", name: "Peri-Peri Chicken Plate", category: "African Meals", price: 65, available: true, imageUrl: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=80" },
  { id: "13", name: "Samp & Beans Bowl", category: "African Meals", price: 52, available: true, imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80" },
  { id: "14", name: "Kota Quarter", category: "Street Food", price: 55, available: true, imageUrl: "https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&w=900&q=80" },
  { id: "3", name: "Iced Latte", category: "Drinks", price: 28, available: true, imageUrl: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=80" },
  { id: "4", name: "Cheese Scone", category: "Snacks", price: 22, available: false, imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=80" },
  { id: "5", name: "Fruit Smoothie", category: "Drinks", price: 30, available: true, imageUrl: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=900&q=80" },
  { id: "10", name: "Mango Smoothie", category: "Smoothies", price: 35, available: true, imageUrl: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=900&q=80" },
  { id: "11", name: "Berry Smoothie", category: "Smoothies", price: 38, available: true, imageUrl: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=900&q=80" },
];

export const vendorMenuById: Record<string, FoodItem[]> = {
  "fresh-bites": [
    {
      id: "chicken-wrap",
      name: "Chicken Wrap",
      vendor: "Fresh Bites",
      vendorId: "fresh-bites",
      price: 45,
      category: "Meals",
      description: "Grilled chicken, crunchy slaw, and chilli mayo.",
      available: true,
      accent: "from-violet-100 to-violet-200",
      imageUrl: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "pap-chakalaka",
      name: "Pap & Chakalaka",
      vendor: "Fresh Bites",
      vendorId: "fresh-bites",
      price: 48,
      category: "African Meals",
      description: "Soft maize pap served with spicy chakalaka relish.",
      available: true,
      accent: "from-amber-100 to-orange-100",
      imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "vetkoek-mince",
      name: "Vetkoek & Mince",
      vendor: "Fresh Bites",
      vendorId: "fresh-bites",
      price: 42,
      category: "Street Food",
      description: "Golden fried dough filled with savoury spiced mince.",
      available: true,
      accent: "from-orange-100 to-rose-100",
      imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "peri-peri-chicken",
      name: "Peri-Peri Chicken Plate",
      vendor: "Fresh Bites",
      vendorId: "fresh-bites",
      price: 65,
      category: "African Meals",
      description: "Chargrilled chicken with peri-peri sauce and seasoned sides.",
      available: true,
      accent: "from-red-100 to-orange-100",
      imageUrl: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "chicken-livers-pap",
      name: "Chicken Livers & Pap",
      vendor: "Fresh Bites",
      vendorId: "fresh-bites",
      price: 50,
      category: "African Meals",
      description: "Tender spicy chicken livers with creamy maize pap.",
      available: true,
      accent: "from-orange-100 to-yellow-100",
      imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "veggie-wrap",
      name: "Veggie Wrap",
      vendor: "Fresh Bites",
      vendorId: "fresh-bites",
      price: 38,
      category: "Meals",
      description: "Fresh vegetables with a light herb dressing.",
      available: true,
      accent: "from-emerald-100 to-violet-100",
      imageUrl: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=80",
    },
  ],
  "mamas-corner": [
    {
      id: "beef-bowl",
      name: "Beef Rice Bowl",
      vendor: "Mama's Corner",
      vendorId: "mamas-corner",
      price: 62,
      category: "Meals",
      description: "Tender beef, rice, and seasonal vegetables.",
      available: true,
      accent: "from-fuchsia-100 to-violet-100",
      imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "miso-noodle",
      name: "Miso Noodle Cup",
      vendor: "Mama's Corner",
      vendorId: "mamas-corner",
      price: 52,
      category: "Meals",
      description: "Comforting noodles in a rich miso broth.",
      available: true,
      accent: "from-violet-100 to-indigo-100",
      imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "beef-bunny-chow",
      name: "Beef Bunny Chow",
      vendor: "Mama's Corner",
      vendorId: "mamas-corner",
      price: 58,
      category: "African Meals",
      description: "Durban-style curry served inside a fresh quarter loaf.",
      available: true,
      accent: "from-orange-100 to-fuchsia-100",
      imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "chicken-samoosa",
      name: "Chicken Samoosas",
      vendor: "Mama's Corner",
      vendorId: "mamas-corner",
      price: 30,
      category: "Snacks",
      description: "Crisp pastry triangles filled with spiced chicken.",
      available: true,
      accent: "from-amber-100 to-violet-100",
      imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "lamb-bunny-chow",
      name: "Lamb Bunny Chow",
      vendor: "Mama's Corner",
      vendorId: "mamas-corner",
      price: 68,
      category: "African Meals",
      description: "Slow-cooked lamb curry served in a fresh bread loaf.",
      available: true,
      accent: "from-amber-100 to-red-100",
      imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "samp-beans",
      name: "Samp & Beans Bowl",
      vendor: "Mama's Corner",
      vendorId: "mamas-corner",
      price: 52,
      category: "African Meals",
      description: "Comforting samp and beans finished with a savoury relish.",
      available: true,
      accent: "from-yellow-100 to-orange-100",
      imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80",
    },
  ],
  "student-cafe": [
    {
      id: "iced-latte",
      name: "Iced Latte",
      vendor: "Student Café",
      vendorId: "student-cafe",
      price: 28,
      category: "Drinks",
      description: "Smooth and chilled for busy campus hours.",
      available: true,
      accent: "from-violet-50 to-indigo-100",
      imageUrl: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "cheese-scone",
      name: "Cheese Scone",
      vendor: "Student Café",
      vendorId: "student-cafe",
      price: 22,
      category: "Snacks",
      description: "Warm, flaky, and easy to grab on the move.",
      available: false,
      accent: "from-violet-100 to-pink-100",
      imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "rooibos-iced-tea",
      name: "Iced Rooibos Tea",
      vendor: "Student Café",
      vendorId: "student-cafe",
      price: 24,
      category: "Traditional Drinks",
      description: "Chilled South African rooibos tea with citrus.",
      available: true,
      accent: "from-red-100 to-orange-100",
      imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "malva-pudding",
      name: "Malva Pudding",
      vendor: "Student Café",
      vendorId: "student-cafe",
      price: 35,
      category: "Desserts",
      description: "Warm apricot sponge with a sweet custard pour.",
      available: true,
      accent: "from-amber-100 to-pink-100",
      imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "amagwinya-bites-cafe",
      name: "Amagwinya Bites",
      vendor: "Student Café",
      vendorId: "student-cafe",
      price: 26,
      category: "Snacks",
      description: "Mini vetkoek served warm with a sweet chilli dip.",
      available: true,
      accent: "from-yellow-100 to-orange-100",
      imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "koeksister",
      name: "Cape Koeksister",
      vendor: "Student Café",
      vendorId: "student-cafe",
      price: 20,
      category: "Desserts",
      description: "Traditional syrup-soaked twisted dough with coconut.",
      available: true,
      accent: "from-amber-100 to-pink-100",
      imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=80",
    },
  ],
  "sunset-snacks": [
    {
      id: "fruit-smoothie",
      name: "Fruit Smoothie",
      vendor: "Sunset Snacks",
      vendorId: "sunset-snacks",
      price: 30,
      category: "Drinks",
      description: "Refreshing fruit blend for a quick boost.",
      available: true,
      accent: "from-pink-100 to-violet-100",
      imageUrl: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "boerewors-roll",
      name: "Boerewors Roll",
      vendor: "Sunset Snacks",
      vendorId: "sunset-snacks",
      price: 46,
      category: "Street Food",
      description: "Grilled boerewors in a soft roll with tomato relish.",
      available: true,
      accent: "from-red-100 to-orange-100",
      imageUrl: "https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "amagwinya",
      name: "Amagwinya Bites",
      vendor: "Sunset Snacks",
      vendorId: "sunset-snacks",
      price: 26,
      category: "Snacks",
      description: "Mini vetkoek bites served with a sweet chilli dip.",
      available: true,
      accent: "from-yellow-100 to-orange-100",
      imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "mango-smoothie",
      name: "Mango Smoothie",
      vendor: "Sunset Snacks",
      vendorId: "sunset-snacks",
      price: 35,
      category: "Smoothies",
      description: "Creamy mango blended with yoghurt and a touch of citrus.",
      available: true,
      accent: "from-yellow-100 to-orange-100",
      imageUrl: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "berry-smoothie",
      name: "Berry Smoothie",
      vendor: "Sunset Snacks",
      vendorId: "sunset-snacks",
      price: 38,
      category: "Smoothies",
      description: "A chilled blend of berries, banana, and yoghurt.",
      available: true,
      accent: "from-pink-100 to-red-100",
      imageUrl: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "kota-quarter",
      name: "Kota Quarter",
      vendor: "Sunset Snacks",
      vendorId: "sunset-snacks",
      price: 55,
      category: "Street Food",
      description: "A loaded quarter loaf with chips, egg, and spicy relish.",
      available: true,
      accent: "from-orange-100 to-red-100",
      imageUrl: "https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "mahewu-drink",
      name: "Mahewu Cooler",
      vendor: "Sunset Snacks",
      vendorId: "sunset-snacks",
      price: 22,
      category: "Traditional Drinks",
      description: "A chilled, lightly sweet fermented maize drink.",
      available: true,
      accent: "from-yellow-100 to-amber-100",
      imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=80",
    },
  ],
};
